#!/usr/bin/env python3

import ClassDraft4 as cd

import argparse
parser = argparse.ArgumentParser()

parser.add_argument("-t",
                    "--target",
                    help = "Takes the name of a target as a string. The only "+
                    "acceptable name format is 'name'. ",
                    type = str)

parser.add_argument("-d",
                    "--days",
                    help = "Takes an interget number of days. Checks target"+
                    "visibility for that number of days after the script is "+
                    "run. Defaults to a week.",
                    type = int,
                    default = 7)


args = parser.parse_args()

################################################################################


target = cd.targets.target_from_name(args.target)

day_check = cd.schedule.day_check(target , args.days)


################################################################################
